wip: expose worker options
crowdsecurity/cs-cloudflare-worker-bouncer pull request #30
Opened 2024-02-28 10:59 UTC by LaurenceJJones

Fix #24

2024-04-25 07:22 UTC, buixor requested changes

2024-04-25 07:22 UTC, buixor commented on cmd/root.go
> +	cfManagers := make([]*cf.CloudflareAccountManager, len(config.Accounts))
beware, `make(x, y)` means that `len(x)` = `y`. You are using `append` bellow so it will append after the y'th element.

2024-04-25 07:22 UTC, buixor commented on go.mod
> +	github.com/crowdsecurity/crowdsec v1.6.0
1.6.1 ?

2024-04-25 07:34 UTC, LaurenceJJones commented on cmd/root.go
> +	cfManagers := make([]*cf.CloudflareAccountManager, len(config.Accounts))
`make(x, 0, y)` then?

2024-04-25 07:35 UTC, LaurenceJJones commented on go.mod
> +	github.com/crowdsecurity/crowdsec v1.6.0
I can update it, i made PR before `1.6.1`

2024-06-18 13:05 UTC, buixor approved these changes

2024-06-18 13:06 UTC, merged